1. Take marks as input (0–100). Use if-elif-else to print the grade: 
    90–100 → A 
    75–89 → B 
    50–74 → C 
    Below 50 → Fail

In [ ]:
mark=int(input("Enter your marks:"))
if mark<=100 and mark>=90:
    print("Grade-A")
elif mark<=89 and mark>=75:
    print("Grade-B")
elif mark<=74 and mark>=50:
    print("Grade-C")
else:
    print("Fail")

## 2. Accept a number from the user and use a while loop to find the sum of its digits. 

In [12]:
num=int(input("Enter a number:"))
sum=0
while num>0:
    d=num%10
    sum+=d
    num=num//10
print(sum)

7


### 3. Write a function is_prime(n) that returns True if a number is prime, otherwise False.Test it for multiple values

In [19]:
def is_prime(n):
    f=0
    for i in range(1,n+1):
        if n%i==0:
            f=f+1
    return f==2


print(is_prime(17))


True


## 4. Define a function is_palindrome(word) that checks whether a string is a palindrome or not. Example: "madam" → Palindrome.

In [ ]:
def is_palindrome(s: str):
    s=s.lower()
    return s==s[ : :-1]
print(is_palindrome("madam"))

False


In [ ]:
!pip install numpy

In [7]:
'''
Create two 3×3 matrices and perform: 
a) Matrix multiplication 
b) Determinant of a matrix 
c) Inverse of a matrix (if possible)
'''

import numpy as np

X=np.array([[1,2,3],
            [1,2,3],
            [1,2,3]])
Y=np.array([[3,2,1],
            [3,2,1],
            [3,2,1]])

#Matrix Multiplication : 

Z=np.dot(X,Y)
print(Z)

[[18 12  6]
 [18 12  6]
 [18 12  6]]
