In [17]:
#Printing squares of integers from 1 to 3
for i in[1,2,3]:
    print(i*i,end=" ")
    

1 4 9 

In [16]:

for i in range(1,5):
    print(i, end=" ")

1 2 3 4 

In [25]:
i=4
while(i>0):
    print(i,end=" ")
    i-=1;

4 3 2 1 

In [33]:
#factorial
def factorial(n):
    fact=1
    for i in range(1,n+1):
        fact*=i;
    return (fact);

print(factorial(5))

120


# Numpy Library

In [34]:
#Importing numpy library
import numpy as np

In [35]:
x=np.array([1,2,3])
print(x)

[1 2 3]


In [36]:
#Numpy arrays are faster than lists
x=list(range(1000000))
y=np.array(x)
%timeit sum(x)
%timeit np.sum(y)

7.33 ms ± 13.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
331 µs ± 7.84 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [41]:
data=np.array([1.5,-3,35])
print(data, "\nType : ",type(data))

[ 1.5 -3.  35. ] 
Type :  <class 'numpy.ndarray'>


In [47]:
arr=np.array([[1,2,3,4],[5,4,3,2],[4,5,3,3]])
print(arr)

[[1 2 3 4]
 [5 4 3 2]
 [4 5 3 3]]
