In [1]:
import numpy as np


In [2]:
arr=([1,2,3,4,5])
print(arr)

[1, 2, 3, 4, 5]


In [3]:
print(np.__version__)

1.24.3


In [4]:
print(type(arr))

<class 'list'>


In [5]:
#Using a tuple to create a numpy array
tu=np.array((1,2,3,"dog"))
print(tu)
print(type(tu))

['1' '2' '3' 'dog']
<class 'numpy.ndarray'>


# Dimensions In Array

In [6]:
#0-D Array: 
a=np.array(34)
print(type(a),"\n0-D Arr: ",a)


<class 'numpy.ndarray'> 
0-D Arr:  34


In [7]:
#1-D Array:
ar=np.array([1,2,3,4])
print(ar)

[1 2 3 4]


In [8]:
#2-D Array:
arr2=np.array([[1,2,3,4],[4,3,2,1]])
print(arr2)

[[1 2 3 4]
 [4 3 2 1]]


In [9]:
#to check dimensions of N-Dim-Array:
print(a.ndim)
print(ar.ndim)
print(arr2.ndim)

0
1
2


# NumPy Array Indexing

In [10]:
import numpy as np

In [11]:
ar=np.array([[2,3,4],[2,1,5]])
print(ar)
print(type(ar))
print(ar.ndim)
print("Shape: ",ar.shape)
print("At Index ar(0,0)= ",ar[0,0])

[[2 3 4]
 [2 1 5]]
<class 'numpy.ndarray'>
2
Shape:  (2, 3)
At Index ar(0,0)=  2


# NumPy Data Types

In [12]:
import numpy as np

In [13]:
#integer
arr=np.array([12,3,4,2])
print(arr.dtype)

int64


In [14]:
#string
arr=np.array(["abcd","xyz"])
print(arr.dtype)

<U4


In [15]:
#Creating Arrays with a defined data type : 
arr=np.array([12,34,2,0], dtype="S")
print(arr)
print(arr.dtype)

'''
The numbers [12, 34, 2, 0] are converted to their string representations: "12", "34", "2", "0"
The longest string here is "12" or "34", which has 2 chars. So NumPy assigns the datatype to |S2 as 
byte string of length 2.
'''

[b'12' b'34' b'2' b'0']
|S2


'\nThe numbers [12, 34, 2, 0] are converted to their string representations: "12", "34", "2", "0"\nThe longest string here is "12" or "34", which has 2 chars. So NumPy assigns the datatype to |S2 as \nbyte string of length 2.\n'

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [17]:
arr = np.array(["1", "2", "3", "4"], dtype='i')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32
