In [1]:
import numpy as np
num=np.array([2,3,5,7,11])
print(num)

[ 2  3  5  7 11]


In [2]:
type(num)

numpy.ndarray

In [3]:
two_d_array=np.array([[1,2,3],[4,5,6]])
print(two_d_array)
type(two_d_array)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

## Array Attributes

In [4]:
integers=np.array([[1,2,3],[4,5,6]])
print("matrix:",integers)
print("dtype:",integers.dtype)
print("dimension:",integers.ndim)
print("shape:",integers.shape)
print("No Of Elements:",integers.size)
print("",integers.itemsize)

matrix: [[1 2 3]
 [4 5 6]]
dtype: int64
dimension: 2
shape: (2, 3)
No Of Elements: 6
 8


In [5]:
floats=np.array([0.000,0.300,0.1,0.5]) #trailing 0s are not printed in numpy
print("matrix:",floats)
print("dtype:",floats.dtype)
print("dimension:",floats.ndim)
print("shape:",floats.shape)
print("No Of Elements:",floats.size)
print("",floats.itemsize)

matrix: [0.  0.3 0.1 0.5]
dtype: float64
dimension: 1
shape: (4,)
No Of Elements: 4
 8


In [6]:
#iterating through a multidimensional array : 
for row in integers:
    for column in row:
        print(column, end=" ")
    print()

1 2 3 
4 5 6 


In [7]:
#flat : converts ndim to 1-d array
for i in integers.flat:
    print(i,end=" ")

1 2 3 4 5 6 

In [8]:
import numpy as np
z=np.zeros(4)
print(z)
o=np.ones(5)
print(o)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [9]:
x=np.arange(5)
print(x)
y=np.arange(5,20)
print(y)
z=np.arange(1,11,2)
print(z)

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 3 5 7 9]


In [10]:
#linspace
a=np.linspace(0,1,num=5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [11]:
mat1=np.arange(1,21).reshape(4,5)
print(f"Shape: {mat1.shape}\n {mat1}")
mat1=np.arange(1,21).reshape(2,10)
print(f"Shape: {mat1.shape}\n {mat1}")

Shape: (4, 5)
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape: (2, 10)
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [12]:
mat2=np.arange(1,100001).reshape(100,1000)
print(mat2)

[[     1      2      3 ...    998    999   1000]
 [  1001   1002   1003 ...   1998   1999   2000]
 [  2001   2002   2003 ...   2998   2999   3000]
 ...
 [ 97001  97002  97003 ...  97998  97999  98000]
 [ 98001  98002  98003 ...  98998  98999  99000]
 [ 99001  99002  99003 ...  99998  99999 100000]]


In [13]:
numbers=np.arange(1,6)
print(numbers)
print(numbers*3) #broadcasting happens to the scalar values performing the operation in each element
print(numbers**2)

[1 2 3 4 5]
[ 3  6  9 12 15]
[ 1  4  9 16 25]


In [14]:
#Arithmetic Operations
num=np.linspace(1.1,5.5,5)
print(num)
print(num*numbers)

[1.1 2.2 3.3 4.4 5.5]
[ 1.1  4.4  9.9 17.6 27.5]


In [15]:
#Comparing Arrays:
print(numbers)
print(numbers>=13)
print(num)
print(num<numbers)
print(num==numbers)

[1 2 3 4 5]
[False False False False False]
[1.1 2.2 3.3 4.4 5.5]
[False False False False False]
[False False False False False]


In [16]:
grades=np.array([[67,87,45],[76,86,69],[87,68,97],[86,90,60]])
print(grades)
print(grades.sum())
print(grades.min())
print(grades.max())
print(grades.mean())
print(grades.std())

[[67 87 45]
 [76 86 69]
 [87 68 97]
 [86 90 60]]
918
45
97
76.5
14.396180048887969


In [17]:
num=np.arange(1,7)
num2=num.copy()
print(f"num: {num} id: {id(num)}")
print(f"num.copy(): {num2} id: {id(num2)}")

num: [1 2 3 4 5 6] id: 127836713722384
num.copy(): [1 2 3 4 5 6] id: 127836713679824


`Shallow Copy : The array method view returns a new array object with a   view of the original array object data`

`Reshape & resize : both methods are used to change the array dimension`

`reshape()-> returns a view (shallow copy) of the original array with new dimensions, it doesn't modify the original array 
resize()-> modifies the original array`

In [18]:
num=np.arange(1,7)
print(num)
print(num.reshape(2,3))
print(num.resize(2,3))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
None


`flatten() is used to flatten a multi-D array into 1-D array`
`It deep copies the original array's data`

In [19]:
grades=np.array([[87,96,70],[100,87,60]])
print("grades:\n",grades)
flattened=grades.flatten()
print("flattened: ",flattened)

grades:
 [[ 87  96  70]
 [100  87  60]]
flattened:  [ 87  96  70 100  87  60]


In [20]:
#now if we change value in flattened wouldn't affect the original grade array
flattened[2]=23; #flattened is a deep copy of grades
print(flattened)
print(grades)

[ 87  96  23 100  87  60]
[[ 87  96  70]
 [100  87  60]]


In [21]:
grades=np.array([[87,96,70],[100,87,60]])
print("grades:\n",grades)
flattened=grades.ravel()
print("flattened: ",flattened)

grades:
 [[ 87  96  70]
 [100  87  60]]
flattened:  [ 87  96  70 100  87  60]


In [22]:
#now if we change value in flattened then same change is there in orginal array
flattened[2]=23; #flattened is a shallow copy of grades
print(flattened)
print(grades)

[ 87  96  23 100  87  60]
[[ 87  96  23]
 [100  87  60]]


`The T attribute returns a transpose view(Shallow Copy) of Original Array`

In [49]:
grades=np.array([[87,96,70],[100,87,60]])
print(grades)
print(grades.transpose())

[[ 87  96  70]
 [100  87  60]]
[[ 87 100]
 [ 96  87]
 [ 70  60]]


`Stacking means combining arrays by adding more columns and more rows`

In [24]:
grades2=np.array([[23,64,75],[67,37,86]])
print("Horizontal Stack:\n",np.hstack((grades,grades2)))
print("Vertical Stack:\n",np.vstack(((grades,grades2))))

Horizontal Stack:
 [[ 87  96  70  23  64  75]
 [100  87  60  67  37  86]]
Vertical Stack:
 [[ 87  96  70]
 [100  87  60]
 [ 23  64  75]
 [ 67  37  86]]


In [25]:
#Series is a 1-D array
import pandas as pd
grades=pd.Series([87,100,78])
print(grades)

0     87
1    100
2     78
dtype: int64


In [26]:
#Series with All Elements having same value
g1=pd.Series(98.6,range(3))
print(g1)

0    98.6
1    98.6
2    98.6
dtype: float64


In [27]:
#Accessing the index:
print(grades[2])

78


In [28]:
print("grades: \n",grades)
print("\nSum: ",grades.sum())
print("Minimum: ",grades.min())
print("Maximum: ",grades.max())
print("Mean: ",grades.mean())
print("Std Deviation: ",grades.std())

grades: 
 0     87
1    100
2     78
dtype: int64

Sum:  265
Minimum:  78
Maximum:  100
Mean:  88.33333333333333
Std Deviation:  11.06044001535804


In [29]:
grades.describe()
''' 
25%, 50%, 75% are quartiles
'''

' \n25%, 50%, 75% are quartiles\n'

In [30]:
#Series with custom indices
grades=pd.Series([87,100,93], index=['Ally','Willy','Billy'])
print(grades)

Ally      87
Willy    100
Billy     93
dtype: int64


In [31]:
#A series can be initialized with a dict
#keys -> Series' indices
#values -> Series' element
print(grades['Ally'])
print(grades.Ally)
print(grades.dtype)

87
87
int64


In [32]:
#A Series of Strings
hardware= pd.Series(['Hammer','Saw','Wrench'])
print(hardware)

0    Hammer
1       Saw
2    Wrench
dtype: object


In [33]:
print("All in Upper Case: \n",hardware.str.upper())
print("\nin Lower Case: \n",hardware.str.lower())

All in Upper Case: 
 0    HAMMER
1       SAW
2    WRENCH
dtype: object

in Lower Case: 
 0    hammer
1       saw
2    wrench
dtype: object


### DataFrame

In [57]:
import pandas as pd
#DataFrame from dict
grades_dict={'Wally':[87,67,98],'Bally':[23,86,68],'Gally':[86,57,48]}
grades=pd.DataFrame(grades_dict)
print(grades)

   Wally  Bally  Gally
0     87     23     86
1     67     86     57
2     98     68     48


In [58]:
grades.index=['Test1','Test2','Test3']
print(grades)

       Wally  Bally  Gally
Test1     87     23     86
Test2     67     86     57
Test3     98     68     48


In [59]:
#for loc we take index in String as input 
grades.loc['Test1']

Wally    87
Bally    23
Gally    86
Name: Test1, dtype: int64

In [60]:
#iloc takes index as int 
grades.iloc[0]

Wally    87
Bally    23
Gally    86
Name: Test1, dtype: int64

In [61]:
grades.loc['Test1':'Test2']

Wally  Bally  Gally
Test1     87     23     86
Test2     67     86     57

In [62]:
grades.iloc[0:2]

Wally  Bally  Gally
Test1     87     23     86
Test2     67     86     57

In [40]:
grades.loc['Test1':'Test2',['Wally','Bally']]

Wally  Bally
Test1     87     23
Test2     67     86

In [41]:
grades.iloc[[0,2],0:2]

Wally  Bally
Test1     87     23
Test3     98     68

In [42]:
#Boolean Indexing
grades[grades>=60]

Wally  Bally  Gally
Test1     87    NaN   86.0
Test2     67   86.0    NaN
Test3     98   68.0    NaN

In [63]:
#at -> used for any index(Eg. str idx)
print(grades.at['Test2','Wally'])

67


In [44]:
#iat -> used for int index only
print(grades.iat[1,0])

67


In [46]:
#.describe
pd.set_option('precision',2)
print(grades.describe())

       Wally  Bally  Gally
count   3.00   3.00   3.00
mean   84.00  59.00  63.67
std    15.72  32.45  19.86
min    67.00  23.00  48.00
25%    77.00  45.50  52.50
50%    87.00  68.00  57.00
75%    92.50  77.00  71.50
max    98.00  86.00  86.00


In [47]:
#Transposing the DataFrames with the T attributes
print(grades.T)

       Test1  Test2  Test3
Wally     87     67     98
Bally     23     86     68
Gally     86     57     48


In [50]:
print(grades.mean())

83.33333333333333


In [64]:
#Sorting 
grades.sort_index(ascending=False)

Wally  Bally  Gally
Test3     98     68     48
Test2     67     86     57
Test1     87     23     86

In [65]:
grades.sort_index(axis=1)

Bally  Gally  Wally
Test1     23     86     87
Test2     86     57     67
Test3     68     48     98

In [66]:
#Sorting by Column Values
grades.sort_values(by='Test1',axis=1,ascending=False)


Wally  Gally  Bally
Test1     87     86     23
Test2     67     57     86
Test3     98     48     68