In [1]:
import numpy as np
num=np.array([2,3,5,7,11])
print(num)

[ 2  3  5  7 11]


In [2]:
type(num)

numpy.ndarray

In [4]:
two_d_array=np.array([[1,2,3],[4,5,6]])
print(two_d_array)
type(two_d_array)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

## Array Attributes

In [22]:
integers=np.array([[1,2,3],[4,5,6]])
print("matrix:",integers)
print("dtype:",integers.dtype)
print("dimension:",integers.ndim)
print("shape:",integers.shape)
print("No Of Elements:",integers.size)
print("",integers.itemsize)

matrix: [[1 2 3]
 [4 5 6]]
dtype: int64
dimension: 2
shape: (2, 3)
No Of Elements: 6
 8


In [18]:
floats=np.array([0.000,0.300,0.1,0.5]) #trailing 0s are not printed in numpy
print("matrix:",floats)
print("dtype:",floats.dtype)
print("dimension:",floats.ndim)
print("shape:",floats.shape)
print("No Of Elements:",floats.size)
print("",floats.itemsize)

[0.  0.3 0.1 0.5]
float64
1


In [23]:
#iterating through a multidimensional array : 
for row in integers:
    for column in row:
        print(column, end=" ")
    print()

1 2 3 
4 5 6 


In [24]:
#flat : converts ndim to 1-d array
for i in integers.flat:
    print(i,end=" ")

1 2 3 4 5 6 

In [33]:
import numpy as np
z=np.zeros(4)
print(z)
o=np.ones(5)
print(o)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [38]:
x=np.arange(5)
print(x)
y=np.arange(5,20)
print(y)
z=np.arange(1,11,2)
print(z)

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 3 5 7 9]


In [44]:
#linspace
a=np.linspace(0,1,num=5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [48]:
mat1=np.arange(1,21).reshape(4,5)
print(f"Shape: {mat1.shape}\n {mat1}")
mat1=np.arange(1,21).reshape(2,10)
print(f"Shape: {mat1.shape}\n {mat1}")

Shape: (4, 5)
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape: (2, 10)
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [49]:
mat2=np.arange(1,100001).reshape(100,1000)
print(mat2)

[[     1      2      3 ...    998    999   1000]
 [  1001   1002   1003 ...   1998   1999   2000]
 [  2001   2002   2003 ...   2998   2999   3000]
 ...
 [ 97001  97002  97003 ...  97998  97999  98000]
 [ 98001  98002  98003 ...  98998  98999  99000]
 [ 99001  99002  99003 ...  99998  99999 100000]]


In [54]:
numbers=np.arange(1,6)
print(numbers)
print(numbers*3) #broadcasting happens to the scalar values performing the operation in each element
print(numbers**2)

[1 2 3 4 5]
[ 3  6  9 12 15]
[ 1  4  9 16 25]


In [57]:
#Arithmetic Operations
num=np.linspace(1.1,5.5,5)
print(num)
print(num*numbers)

[1.1 2.2 3.3 4.4 5.5]


array([ 1.1,  4.4,  9.9, 17.6, 27.5])

In [62]:
#Comparing Arrays:
print(numbers)
print(numbers>=13)
print(num)
print(num<numbers)
print(num==numbers)

[1 2 3 4 5]
[False False False False False]
[1.1 2.2 3.3 4.4 5.5]
[False False False False False]
[False False False False False]


In [66]:
grades=np.array([[67,87,45],[76,86,69],[87,68,97],[86,90,60]])
print(grades)
print(grades.sum())
print(grades.min())
print(grades.max())
print(grades.mean())
print(grades.std())

[[67 87 45]
 [76 86 69]
 [87 68 97]
 [86 90 60]]
918
45
97
76.5
14.396180048887969
