 ```1. Take marks as input (0–100). Use if-elif-else to print the grade: 
    90–100 → A 
    75–89 → B 
    50–74 → C 
    Below 50 → Fail```

In [ ]:
mark=int(input("Enter your marks:"))
if mark<=100 and mark>=90:
    print("Grade: A")
elif mark<=89 and mark>=75:
    print("Grade: B")
elif mark<=74 and mark>=50:
    print("Grade: C")
else:
    print("Fail")

```2. Accept a number from the user and use a while loop to find the sum of its digits.```

In [ ]:
num=int(input("Enter a number:"))
sum=0
while num>0:
    d=num%10
    sum+=d
    num=num//10
print(sum)

3. Write a function is_prime(n) that returns True if a number is prime, otherwise False.Test it for multiple values

In [ ]:
def is_prime(n):
    f=0
    for i in range(1,n+1):
        if n%i==0:
            f=f+1
    return f==2


print(is_prime(17))


```4. Define a function is_palindrome(word) that checks whether a string is a palindrome or not. Example: "madam" → Palindrome.```

In [ ]:
def is_palindrome(s: str):
    s=s.lower()
    return s==s[ : :-1]
print(is_palindrome("madam"))

```5. Create two 3×3 matrices and perform: 
a) Matrix multiplication 
b) Determinant of a matrix 
c) Inverse of a matrix (if possible)```

In [ ]:
!pip install numpy

In [49]:
import numpy as np

X=np.array([[1,0,0],
            [3,3,0],
            [5,2,-1]])

Y=np.array([[3,2,1],
            [3,2,1],
            [3,2,1]])

#Matrix Multiplication : 
print("Multiplication: ")
Z=np.dot(X,Y)
print(Z)

#Determinant Of A Matrix :
det_X=np.linalg.det(X)
print("Determinant of X:",det_X)
det_Y=np.linalg.det(Y)
print("Determinant of Y:",det_Y)

#Inverse Of A Matrix(If Exists) :
print("Original Mat: \n",X)
if np.isclose(det_X,0):
    print("Matrix is Singular.Inverse is not possible")
else:
    inv_X=np.linalg.inv(X)
    print("Inverse: \n",inv_X)
    print("Verifying: \n",np.round(np.dot(inv_X,X),decimals=8))

Multiplication: 
[[ 3  2  1]
 [18 12  6]
 [18 12  6]]
Determinant of X: -2.9999999999999996
Determinant of Y: 0.0
Original Mat: 
 [[ 1  0  0]
 [ 3  3  0]
 [ 5  2 -1]]
Inverse: 
 [[ 1.00000000e+00  2.22044605e-17  0.00000000e+00]
 [-1.00000000e+00  3.33333333e-01  0.00000000e+00]
 [ 3.00000000e+00  6.66666667e-01 -1.00000000e+00]]
Verifying: 
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]


```
6. Generate two NumPy arrays of 10 random integers each. Perform element-wise
comparison (>, <, ==). Count how many times values in the first array are greater than the second.
```

In [45]:
import numpy as np
import random

arr1=[]
arr2=[]
for i in range(10):
    arr1.append(random.randint(1,20))
    arr2.append(random.randint(1,20))
arr1=np.array(arr1)
arr2=np.array(arr2)
count=0
for i in range(10):
    if arr1[i]>arr2[i]:
        count=count+1
print(count)

3


In [57]:
import random
arr1=np.random.randint(0, 10, size=10)
arr2=np.random.randint(0,10,size=10)
print("arr1= ",arr1,"\narr2= ",arr2)
greater_than=arr1>arr2
g=np.sum(greater_than)
print(g)

arr1[]=  [4 2 0 6 0 6 5 6 9 6] 
arr2[]=  [7 6 0 8 0 7 8 0 1 4]
3


```Suppose you have exam marks of 10 students stored in a Python list. Convert it into a
NumPy array and compute:
a) Average marks of the class
 b) Students who scored above average```

In [ ]:
import numpy as np
marks=[70,80,50,90,78,57,39,78,58,49]
marks=np.array(marks)
mean=np.mean(marks)
print("Mean: ",mean)
        